# Generated by Django 6.1.1 on 2026-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('provider', models.CharField(default='nominatim', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'geocode cache entries',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('source_file', 'Source file'), ('gazetteer', 'US Census gazetteer'), ('nominatim', 'Nominatim')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_latlon_idx'), models.Index(fields=['state', 'city'], name='station_state_city_idx')],
                'constraints': [models.UniqueConstraint(fields=('opis_id', 'city', 'state', 'name'), name='uniq_station_identity')],
            },
        ),
    ]
